### ISSUE TITLE
Unable to start Storefront

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-deprecated#74]
Following the steps [here ](https://virtocommerce.com/docs/vc2devguide/deployment/storefront-deployment/deploy-from-source-code)my Storefront instance does not start.

If I setup an API user with HMAC and enter those details in Storefront's web.config I am greeted with the following error at runtime:

```
Operation returned an invalid status code 'Unauthorized'
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: Operation returned an invalid status code 'Unauthorized'

Source Error: 


Line 582:                    _httpResponse.Dispose();
Line 583:                }
Line 584:                throw ex;
Line 585:            }
Line 586:            // Create Result

Source File: H:\GitHub\brgrz\vc-storefront\VirtoCommerce.Storefront\AutoRestClients\StoreModuleApi.cs    Line: 584 

--

```

If I set it up with Simple auth I am presented with the following error:

```
Line 90:         private static byte[] ConvertHexStringToBytes(string hexString) Line 91:         { Line 92:             return Line 93:                 Enumerable.Range(0, hexString.Length) Line 94:                     .Where(i => i % 2 == 0)
--
```

Also the instructions are not clear whether the CMS module is optional or mandatory (both for Platform and Storefront). I opted not to install it and did not proceed with CMS steps as per Storefront setup. Is it required or not?

**Comment by asvishnyakov** [comment]
Hello @brgrz !

1. Which account you tried to use with storefront? We have built-in account `frontend` for this purpose.
2. CMS module is optional for admin (you may use it to admin your CMS content and may not), but CMS setup required for storefront (otherwise, where it will get pages, styles & scripts for your site?).

**Comment by brgrz** [comment]
Hey, I created a new account as per this article (https://virtocommerce.com/docs/vc2devguide/development-scenarios/working-with-platform-api)

2. Ok, nice to know that, I'd just say it's not something that's explained in the Docs.

**Comment by brgrz** [comment]
Just letting you know that using the `frontend `account worked. But I have no idea why a newly created account wouldn't work.
