### ISSUE TITLE
How do I verify separately that the coupon is available?

### ISSUE THREAD

**Issue by ruyi-kooboo** [VirtoCommerce/vc-storefront-deprecated#75]
Hi, I want to let client know the coupon is available for exist shopping cart before they placed an order, How can I do that? Can I only verify but not calculated? Thanks

**Comment by tatarincev** [comment]
This code does what you asked for
https://github.com/VirtoCommerce/vc-storefront/blob/master/VirtoCommerce.Storefront.Model/Cart/ShoppingCart.cs#L421

**Comment by ruyi-kooboo** [comment]
Thank you for you answer, But if I use it to verify, the price of the shopping cart will change immediately, right? Thanks

**Comment by tatarincev** [comment]
Yes, but you can do that on an clone  of cart:)

**Comment by ruyi-kooboo** [comment]
Okay, I'll try as you say. Thank you very much!
